export const zh: Record<string,string> = {
  "HOME":"首页","My Work":"我的工作","OPERATIONS":"运营管理","Onboarding":"入职管理","Offboarding":"离职管理","COMMUNICATION":"沟通管理","Email Center":"邮件中心","ADMIN":"系统管理","Template Manager":"模板管理","Settings":"设置","Need help?":"需要帮助？","Open support center":"打开支持中心","Search people, cases or tasks…":"搜索人员、事项或任务…","Administrator":"管理员","My Profile":"我的资料","My Signature":"我的签名","Outlook Settings":"Outlook 设置","Preferences":"偏好设置","Log out":"退出登录",
  "MONDAY, 24 AUGUST 2026":"2026年8月24日，星期一","Good afternoon, Rui":"下午好，Rui","Here’s what needs your attention today.":"以下是今天需要您关注的事项。","Quick Action":"快速操作","New Onboarding":"新建入职","New Offboarding":"新建离职","Compose Email":"撰写邮件","Import Excel":"导入 Excel","My Tasks":"我的任务","Assigned to you":"分配给您的工作","Due Soon":"即将到期","Next 7 days":"未来 7 天","Waiting":"等待中","Needs follow-up":"需要跟进","Completed Today":"今日完成","Great progress":"进展顺利","Work assigned to you":"分配给您的工作","View all":"查看全部","View calendar":"查看日历","Upcoming":"近期事项","Key people events":"重要人员事件","Recent Cases":"最近事项","Recently viewed and updated":"最近查看及更新","View all cases":"查看全部事项",
  "Send welcome email":"发送欢迎邮件","Confirm IT account":"确认 IT 账户","Collect laptop return":"回收笔记本电脑","Manager confirmation":"经理确认","Starts employment":"开始任职","Starts internship":"开始实习","Last working day":"最后工作日","Open Case":"打开事项","Open":"待处理","In Progress":"进行中","High":"高","Medium":"中","Low":"低","Due":"截止","PERSON":"人员","CASE TYPE":"事项类型","STATUS":"状态","LAST UPDATED":"最后更新","active cases across your scope":"个权限范围内的活跃事项","Export":"导出","Search onboarding cases…":"搜索入职事项…","Search offboarding cases…":"搜索离职事项…","Status":"状态","Start Date":"入职日期","Team":"团队","Owner":"负责人","Employment Type":"用工类型","Clear":"清除","NAME":"姓名","EMPLOYMENT TYPE":"用工类型","TEAM":"团队","START DATE":"入职日期","LAST WORKING DAY":"最后工作日","OWNER":"负责人","Showing":"显示","of":"共","Employee":"员工","Intern":"实习生","Consultant":"顾问","Preparing":"准备中","Ready":"已就绪","Draft":"草稿","Completed":"已完成","Published":"已发布",
  "Back to Onboarding":"返回入职列表","ONBOARDING CASE":"入职事项","Edit":"编辑","Cancel":"取消","More":"更多","Overview":"概览","Checklist":"清单","Communication":"沟通记录","Files":"文件","History":"历史记录","Personal Information":"个人信息","Full Name":"姓名","Contact Email":"联系邮箱","Employee ID":"员工编号","Phone":"电话","Employment":"雇佣信息","Workload":"工作量","Contract Type":"合同类型","Organization":"组织信息","Lab":"实验室","Role":"职位","Manager":"经理","Work Location":"工作地点","Case Information":"事项信息","Priority":"优先级","Notes":"备注","Permanent":"长期合同","Pending assignment":"待分配","Edit mode":"编辑模式","Review your changes before saving":"保存前请检查修改","Discard":"放弃修改","Save Changes":"保存修改","Onboarding checklist":"入职清单","items completed":"项已完成","Add item":"添加项目","PRE-ONBOARDING":"入职前准备","Contract signed":"合同已签署","Work permit confirmed":"工作许可已确认","IT account":"IT 账户","Laptop":"笔记本电脑","Badge":"工牌","Welcome email":"欢迎邮件","Manager reminder":"经理提醒","IT notification":"IT 通知","Owner:":"负责人：","Task":"任务","All messages linked to this case":"与此事项关联的全部沟通","Prepared":"已准备","Mark as Sent":"标记为已发送","No files uploaded yet":"尚未上传文件","Upload contracts, permits and case documents here.":"在此上传合同、许可及事项文件。","Upload File":"上传文件","Audit history":"审计历史","Start Date changed":"入职日期已修改","Manager changed":"经理已修改","Case created":"事项已创建",
  "Prepare a message from a governed template.":"使用受控模板准备邮件。","Outlook Integration":"Outlook 集成","Default Mail Client":"默认邮件客户端","PERSON / CASE":"人员 / 事项","Starts":"入职日期","Change":"更换","Templates":"模板","available":"个可用","Search templates…":"搜索模板…","All":"全部","Favorites":"收藏","General":"通用","Welcome to the team":"欢迎加入团队","Documents required":"所需文件","Leaving confirmation":"离职确认","Information":"信息","complete":"已完成","RECIPIENTS":"收件人","Locked":"已锁定","Add Recipient":"添加收件人","VARIABLES":"变量","FIRST NAME":"名字","Auto-filled":"自动填充","MANAGER":"经理","ADDITIONAL INFORMATION":"附加信息","Manual":"手动填写","Add optional context…":"添加可选说明…","ATTACHMENTS":"附件","Required":"必需","Add Attachment":"添加附件","Email Preview":"邮件预览","Preview only":"仅预览","SUBJECT":"主题","Dear Michael,":"Michael，您好：","We are pleased to welcome you to our Research Center.":"我们很高兴欢迎您加入研究中心。","Your first working day will be":"您的首个工作日为","Your supervisor will be":"您的直属经理是","Please find our welcome guide attached. We look forward to meeting you.":"请查收随附的欢迎指南。期待与您见面。","Kind regards,":"此致敬礼，","People Operations":"人事运营","All required information is complete":"所有必填信息已完整","Save Draft":"保存草稿","Open in Outlook":"在 Outlook 中打开","Ready to Open in Outlook":"准备在 Outlook 中打开","Review the prepared message before opening your default mail client.":"请在打开默认邮件客户端前检查邮件内容。",
  "Create governed, reusable communication templates.":"创建受控且可复用的沟通模板。","New Template":"新建模板","Category":"分类","Language":"语言","Updated":"已更新","Back to templates":"返回模板列表","EMAIL TEMPLATE":"邮件模板","Duplicate":"复制","Version History":"版本历史","Edit Template":"编辑模板","Variables":"变量","Manage variables":"管理变量","Optional":"可选","Recipients & Subject":"收件人与主题","Body Preview":"正文预览","HTML enabled":"支持 HTML","Current":"当前版本","Restore as new version":"恢复为新版本","Preview":"预览","Manage workspace configuration and access.":"管理工作区配置与访问权限。","Users":"用户","active users":"个活跃用户","Manage people and invitations":"管理成员与邀请","Roles & Permissions":"角色与权限","roles":"个角色","Control access and scopes":"控制访问和数据范围","labs":"个实验室","teams":"个团队","Labs, teams and reporting lines":"实验室、团队与汇报关系","Email Settings":"邮件设置","Default configured":"已配置默认项","Signatures and defaults":"签名与默认设置","Connection and fallback mode":"连接及后备模式","File Storage":"文件存储","Cloud storage active":"云存储已启用","Retention and categories":"保留策略与分类","Excel Mapping":"Excel 映射","saved profiles":"个已保存配置","Import mapping profiles":"导入映射配置","Server-side access control":"服务端访问控制","Workspace roles and scopes are enforced for every data request. Managers see only their assigned team; viewers receive read-only fields.":"每次数据请求都会执行角色与范围检查。经理只能查看被分配的团队，查看者只能读取授权字段。","Active":"已启用","Confirm Changes":"确认修改","You are about to update":"您即将更新","onboarding record.":"的入职记录。","Confirm & Save":"确认并保存"
};

// Extra keys added for the Lovable Cloud rebuild (auth, access denied, sharing).
Object.assign(zh, {
  "Internal Operations":"内部运营","Support & Feedback":"支持与反馈","Contact HR Ops":"联系 HR 运营",
  "Sign Out":"退出登录","My Account":"我的账户","Sign In":"登录","Sign Up":"注册",
  "Email":"邮箱","Password":"密码","Full Name":"姓名","Don't have an account?":"还没有账号？","Have an account?":"已有账号？",
  "Check your inbox to confirm your account, then sign in.":"请查收邮件确认账号后再登录。",
  "Access Pending":"等待开通访问",
  "Your account is not activated in Team Workbench yet. Please contact an administrator to grant access.":"您的账号尚未在 Team Workbench 中激活，请联系管理员开通访问权限。",
  "Back to Sign In":"返回登录","Signing in…":"登录中…","Welcome to Team Workbench":"欢迎使用 Team Workbench",
  "Sign in with your work email to continue.":"请使用工作邮箱登录。","Create an account":"创建账号",
  "Ask an administrator to activate it after signing up.":"注册后请联系管理员激活您的账号。",
  "Search people, tasks, emails":"搜索人员、任务、邮件","Good morning":"早上好","Good afternoon":"下午好","Good evening":"晚上好",
  "Welcome back":"欢迎回来","here is your day at a glance.":"这是您今天的概览。","My Tasks":"我的任务","Due Soon":"即将到期",
  "Waiting":"等待中","Completed Today":"今日完成","Open tasks assigned to you":"分配给您的未完成任务","Due within 14 days":"14 天内到期",
  "Blocked or waiting on others":"被阻塞或等待他人","Finished since midnight":"今天零点以来完成","No open tasks. Enjoy the clarity.":"没有未完成任务，享受清爽的一天。",
  "Upcoming Onboarding":"即将入职","View All":"查看全部","No upcoming onboarding.":"暂无即将入职的人员。","starts":"开始日期",
  "Shared With Me":"与我共享","No shared cases yet.":"暂无共享给您的事项。","Recent Cases":"最近事项","Quick Action":"快捷操作",
  "New Onboarding":"新建入职","Compose Email":"撰写邮件","Add Task":"新建任务","New Offboarding":"新建离职",
  "active cases across your scope":"您权限范围内正在进行的事项","All Status":"全部状态","All Types":"全部类型","All Teams":"全部团队",
  "Clear":"清除","Export Excel":"导出 Excel","No cases found.":"未找到事项。","Create one":"立即创建","adjust filters":"调整筛选条件",
  "PERSON":"人员","TEAM":"团队","DATE":"日期","OWNER":"负责人","STATUS":"状态","PRIORITY":"优先级","TYPE":"类型",
  "Overview":"概览","Checklist":"检查清单","Communication":"沟通记录","Files":"文件","History":"历史记录",
  "Back":"返回","Share":"共享","Share Case":"共享事项","Choose a colleague":"选择同事","Choose access level":"选择访问级别",
  "Viewer":"只读成员","Collaborator":"协作者","Can view case details":"可查看事项详情","Can edit tasks and upload files":"可编辑任务并上传文件",
  "This case has not been shared yet.":"该事项尚未共享。","Remove":"移除","Only the case owner can manage sharing.":"只有事项负责人可以管理共享。",
  "People with access":"拥有访问权限的成员","Mark Done":"标记完成","Reopen":"重新打开","Unassigned":"未分配","Assign":"分配",
  "No checklist items yet.":"暂无检查清单项。","Completed by":"完成人","due":"截止",
  "No communications yet.":"暂无沟通记录。","Send the first email":"发送第一封邮件",
  "Upload File":"上传文件","No files yet. Upload contracts, forms or certificates here.":"暂无文件，请在此上传合同、表单或证明。",
  "Download":"下载","Delete":"删除","Uploading…":"上传中…",
  "No history yet.":"暂无历史记录。","Notes (restricted)":"备注（受限）",
  "Restricted":"受限内容","Restricted field: visible to case owners and collaborators only.":"受限字段：仅事项负责人和协作者可见。",
  "Personal & Contact":"个人与联系方式","Job Details":"职位信息","Timeline":"时间线","First Name":"名","Last Name":"姓",
  "Employee ID":"工号","Phone":"电话","Manager":"直属经理","Employment Type":"雇佣类型","Role / Title":"职位","Location":"地点",
  "Workload":"工作饱和度","Contract Type":"合同类型","Start Date":"开始日期","End Date":"结束日期","Notes":"备注",
  "Create Case":"创建事项","Save":"保存","Cancel":"取消","Close":"关闭","Edit":"编辑","Add User":"添加用户","Edit User":"编辑用户",
  "Title":"头衔","Scope":"数据范围","Status":"状态","Active":"启用","Inactive":"停用","Add":"添加","Save Changes":"保存修改",
  "This email is already registered.":"该邮箱已被注册。","Temporary password (share securely, shown once):":"临时密码（仅显示一次，请安全转达）：",
  "Users":"用户","Roles & Permissions":"角色与权限","Your access level":"您的访问级别","Field":"字段","Old":"旧值","New":"新值",
  "When":"时间","By":"操作人","Shared with":"共享给","removed access":"移除访问",
  "Select Case":"选择事项","Select a template and case to begin":"请选择模板和事项开始",
  "Auto-filled from case data":"已根据事项数据自动填充","Manual":"手动填写","Additional Information":"补充信息",
  "To":"收件人","Cc":"抄送","Subject":"主题","Save Draft":"保存草稿","Open in Outlook":"在 Outlook 中打开","Saved":"已保存",
  "Template":"模板","Category":"类别","Last Updated":"最近更新","Variables":"变量","Body Preview":"正文预览",
  "Recipient Rules":"收件人规则","No templates yet.":"暂无模板。","All Categories":"全部类别",
  "This person is already shared on the case.":"该成员已在共享列表中。","You don't have permission to do that.":"您没有执行该操作的权限。",
  "Case not found or no access.":"事项不存在或您没有访问权限。","Case not found.":"事项不存在。",
  "Something went wrong. Please try again.":"出现问题，请重试。","Loading…":"加载中…",
  "Due":"到期","today":"今天","overdue":"已逾期",
  "Task":"任务","Optional":"可选","Untitled task":"未命名任务",
  "Shared with you by the case owner":"由事项负责人共享给您",
  "Version":"版本","Updated":"更新","Published":"已发布","Draft":"草稿",
  "Signed in as":"当前登录","Date":"日期","Starts":"开始",
  "High":"高","Medium":"中","Low":"低","Preparing":"准备中","In Progress":"进行中","Done":"已完成","Not Started":"未开始","Blocked":"已阻塞","Cancelled":"已取消",
  "Onboarding":"入职管理","Offboarding":"离职管理","Employee":"正式员工","Intern":"实习生","Contractor":"外包人员",
  "All Organization":"整个组织","Assigned Cases":"分配的事项",
  "Confirm your account via the email we sent, then sign in.":"请通过我们发送的邮件确认账号，然后登录。"
});
