import {createFileRoute,useNavigate} from "@tanstack/react-router";
import {useQuery} from "@tanstack/react-query";
import {useServerFn} from "@tanstack/react-start";
import {useMemo,useState} from "react";
import {getPeopleFn} from "@/lib/workbench.functions";
import {useLang} from "@/lib/i18n";
import {fmtDate} from "@/lib/format";
import {Badge,Empty,Icon,Loading} from "@/components/workbench/ui";

export const Route=createFileRoute("/_authenticated/people")({head:()=>({meta:[{title:"People · Team Workbench"}]}),component:PeoplePage});
function PeoplePage(){const {t,lang}=useLang();const nav=useNavigate();const call=useServerFn(getPeopleFn);const {data,isLoading}=useQuery({queryKey:["people"],queryFn:()=>call()});const [q,setQ]=useState("");const [status,setStatus]=useState("");const rows=Array.isArray(data)?data:[];const filtered=useMemo(()=>rows.filter(x=>(!q||[x.displayName,x.email,x.employeeId,x.team,x.role].some(v=>v?.toLowerCase().includes(q.toLowerCase())))&&(!status||x.status===status)),[rows,q,status]);if(isLoading)return <Loading/>;if(data&&!Array.isArray(data))return <Empty icon="lock" title={t("You don't have permission to do that.")}/>;return <div><div className="pagehead"><div><p className="eyebrow">{t("PEOPLE OPERATIONS")}</p><h1>{t("People")}</h1><p>{t("One person, one profile, complete employment history")}</p></div></div><div className="filterbar"><div className="searchbox"><Icon name="search"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder={t("Search people")}/></div><select className="filter" value={status} onChange={e=>setStatus(e.target.value)}><option value="">{t("All Status")}</option>{["planned","active","ending","ended","no_employment"].map(x=><option key={x}>{x}</option>)}</select></div><div className="rosterpanel">{filtered.length?<table className="rostertable"><thead><tr><th>{t("PERSON")}</th><th>{t("Employee ID")}</th><th>{t("Employment Type")}</th><th>{t("TEAM")}</th><th>{t("Role / Title")}</th><th>{t("STATUS")}</th><th>{t("Start Date")}</th><th>{t("End Date")}</th></tr></thead><tbody>{filtered.map(x=><tr key={x.personId} onClick={()=>nav({to:"/people/$personId",params:{personId:x.personId}})}><td><b>{x.displayName}</b><br/><small>{x.email??"—"}</small></td><td>{x.employeeId??"—"}</td><td>{x.employmentType??"—"}</td><td>{x.team}</td><td>{x.role??"—"}</td><td><Badge>{x.status}</Badge></td><td>{fmtDate(x.startDate,lang)}</td><td>{fmtDate(x.endDate,lang)}</td></tr>)}</tbody></table>:<Empty icon="users" title={t("No people found.")}/>}</div></div>}
